[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
markers =
    slow: Slow running tests that should not be run by default.
    integration: Integration tests involving external systems or services.
    concretny: current test.
    db: DB testing.
